name: Exécution du test Behave
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
      
    - name: Configuration de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install behave

    - name: Exécution du test Behave
      run: behave
